# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StockMonitor < Formula
  desc "Professional TUI for real-time stock monitoring"
  homepage "https://github.com/Junrin-Lee/stock-monitor"
  version "1.4.0"
  license "MIT"

  on_macos do
    url "https://github.com/Junrin-Lee/stock-monitor/releases/download/v1.4.0/stock-monitor_1.4.0_Darwin_universal.tar.gz"
    sha256 "a996f150303e70a5d3acbd3e2033da7b27855259fb68a9511d57a79037eeb374"

    def install
      bin.install "stock-monitor"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Junrin-Lee/stock-monitor/releases/download/v1.4.0/stock-monitor_1.4.0_Linux_x86_64.tar.gz"
      sha256 "926b3fe54e98c56867132e258c433268fa80ac645e43fe00843c670fe377aed5"
      def install
        bin.install "stock-monitor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Junrin-Lee/stock-monitor/releases/download/v1.4.0/stock-monitor_1.4.0_Linux_arm64.tar.gz"
      sha256 "62e7e01f1c24b8b37905169cf15a55f65777bc94c440f1afbfc8b1542109fb37"
      def install
        bin.install "stock-monitor"
      end
    end
  end

  test do
    system "#{bin}/stock-monitor", "--version"
  end
end
