# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StockMonitor < Formula
  desc "Professional TUI for real-time stock monitoring"
  homepage "https://github.com/Junrin-Lee/stock-monitor"
  version "1.4.0"
  license "MIT"

  on_macos do
    url "https://github.com/Junrin-Lee/stock-monitor/releases/download/v1.4.0/stock-monitor_1.4.0_Darwin_universal.tar.gz"
    sha256 "8e9eb36a147fe918593cdefb74a4857a28cec049fbd65946dc151f8da16c8bcf"

    def install
      bin.install "stock-monitor"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Junrin-Lee/stock-monitor/releases/download/v1.4.0/stock-monitor_1.4.0_Linux_x86_64.tar.gz"
      sha256 "02ab21b5ff00e85081f83e135814d89963b7b7ab3710c28fbe815503deedb84e"
      def install
        bin.install "stock-monitor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Junrin-Lee/stock-monitor/releases/download/v1.4.0/stock-monitor_1.4.0_Linux_arm64.tar.gz"
      sha256 "ea8218b38a211ea18550a0f72e0737e8776fd0b342b11e05f6da8732434612ee"
      def install
        bin.install "stock-monitor"
      end
    end
  end

  test do
    system "#{bin}/stock-monitor", "--version"
  end
end
