# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StockMonitor < Formula
  desc "Professional TUI for real-time stock monitoring"
  homepage "https://github.com/Junrin-Lee/stock-monitor"
  version "1.4.0"
  license "MIT"

  on_macos do
    url "https://github.com/Junrin-Lee/stock-monitor/releases/download/v1.4.0/stock-monitor_1.4.0_Darwin_universal.tar.gz"
    sha256 "4160f4824987a46c6f699d5bc493ea09d66458547e442de94a677b24f1c912da"

    def install
      bin.install "stock-monitor"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Junrin-Lee/stock-monitor/releases/download/v1.4.0/stock-monitor_1.4.0_Linux_x86_64.tar.gz"
      sha256 "b78ae6d6d89589455418a25ae655e6a25fb70873e92cde5813a7bb4578c7208b"
      def install
        bin.install "stock-monitor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Junrin-Lee/stock-monitor/releases/download/v1.4.0/stock-monitor_1.4.0_Linux_arm64.tar.gz"
      sha256 "3f614aa68a736e24d57c90c894b323041af042763dba1e2f4465615d0b4bf495"
      def install
        bin.install "stock-monitor"
      end
    end
  end

  test do
    system "#{bin}/stock-monitor", "--version"
  end
end
